openapi: "3.0.3"
info:
  title: "Foreign currency exchange rate API"
  version: "1.2.0"
  description: "Foreign currency exchange rate API"
  contact:
    email: "tocka.ayman@outlook.com"
paths:
  /fetch-one:
    get:
      description: "Fetch a single currency exchange rate"
      parameters:
        - name: "from"
          in: "query"
          description: "Base currency 3-letter symbol, defaults to USD"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/Currency"
        - name: "to"
          in: "query"
          description: "Target currency 3-letter symbol"
          required: true
          schema:
            $ref: "#/components/schemas/Currency"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    $ref: "#/components/schemas/Currency"
                  updated:
                    $ref: "#/components/schemas/DateTime"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  result:
                    type: object
                    minProperties: 1
                    maxProperties: 1
                    additionalProperties:
                      type: number
                      format: float
              example:
                base: USD
                result:
                  EUR: 0.82791
                updated: '2021-01-16 16:34:29'
                ms: 4
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "429":
          description: "Rate limit exceeded"
  /fetch-multi:
    get:
      description: "Fetch multiple currency rates at once"
      parameters:
        - name: "from"
          in: "query"
          description: "Base currency 3-letter symbol, defaults to USD"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/Currency"
        - name: "to"
          in: "query"
          description: "Target currencies, comma separated list of 3-letter symbols"
          required: true
          schema:
            $ref: "#/components/schemas/CurrencyList"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    $ref: "#/components/schemas/Currency"
                  updated:
                    $ref: "#/components/schemas/DateTime"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  result:
                    type: object
                    minProperties: 1
                    additionalProperties:
                      type: number
                      format: float
              example:
                base: USD
                results:
                  EUR: 0.82791
                  GBP: 0.73605
                updated: '2021-01-16 16:34:29'
                ms: 8
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "429":
          description: "Rate limit exceeded"
  /fetch-all:
    get:
      description: "Fetch all available currency rates"
      parameters:
        - name: "from"
          in: "query"
          description: "Base currency 3-letter symbol, defaults to USD"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/Currency"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    $ref: "#/components/schemas/Currency"
                  updated:
                    $ref: "#/components/schemas/DateTime"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  results:
                    type: object
                    minProperties: 130
                    additionalProperties:
                      type: number
                      format: float
              example:
                base: USD
                results:
                  AED: 3.67297
                  AFN: 77.11468
                  ALL: 101.78125
                  AMD: 523.67143
                  ANG: 1.78691
                  AOA: 653.45356
                  ARS: 85.74709
                  AUD: 1.29806
                  AWG: 1.79943
                  AZN: 1.70727
                  BAM: 1.62182
                  BBD: 1.99941
                  BDT: 84.84175
                  BGN: 1.61063
                  BHD: 0.37612
                  BIF: 1943.32401
                  BMD: 0.99926
                  BND: 1.32953
                  BOB: 6.88532
                  BRL: 5.29479
                  BSD: 1.00177
                  BTN: 73.22317
                  BWP: 10.98351
                  BZD: 2.01472
                  CAD: 1.27357
                  CDF: 1977.04254
                  CHF: 0.8912
                  CLF: 0.02491
                  CLP: 734.84469
                  CNH: 6.47453
                  CNY: 6.48079
                  COP: 3461.79891
                  CUP: 24.99558
                  CVE: 90.9024
                  CZK: 21.65759
                  DJF: 177.94053
                  DKK: 6.15612
                  DOP: 58.27175
                  DZD: 133.63021
                  EGP: 15.64449
                  ERN: 15.1347
                  ETB: 39.35227
                  EUR: 0.82791
                  FJD: 2.05329
                  FKP: 0.73605
                  GBP: 0.73605
                  GEL: 3.30208
                  GHS: 5.78235
                  GIP: 0.73605
                  GMD: 51.76064
                  GNF: 10080.74488
                  GTQ: 7.78301
                  GYD: 210.42985
                  HKD: 7.75357
                  HNL: 24.12042
                  HRK: 6.19682
                  HTG: 75.90461
                  HUF: 298.21139
                  IDR: 14054.17341
                  ILS: 3.2719
                  INR: 73.16164
                  IQD: 1458.41307
                  IRR: 42031.79744
                  ISK: 129.4936
                  JMD: 144.24702
                  JOD: 0.70779
                  JPY: 103.87016
                  KES: 109.70116
                  KGS: 75.50493
                  KHR: 4047.84337
                  KMF: 406.08715
                  KPW: 900.13249
                  KRW: 1102.13455
                  KWD: 0.30318
                  KYD: 0.81923
                  KZT: 418.85765
                  LAK: 9308.2585
                  LBP: 1509.38466
                  LKR: 194.62682
                  LRD: 167.93022
                  LSL: 15.21787
                  LYD: 4.45341
                  MAD: 8.91064
                  MDL: 17.18902
                  MGA: 3762.10805
                  MKD: 51.00986
                  MMK: 1331.8784
                  MNT: 2853.84955
                  MOP: 8.01634
                  MRU: 36.41764
                  MUR: 39.84837
                  MVR: 15.66392
                  MWK: 773.70087
                  MXN: 19.79604
                  MYR: 4.03732
                  MZN: 74.77698
                  NAD: 15.18769
                  NGN: 380.3327
                  NOK: 8.56904
                  NPR: 117.3193
                  NZD: 1.40232
                  OMR: 0.38422
                  PAB: 0.99926
                  PEN: 3.60165
                  PGK: 3.52819
                  PHP: 48.06492
                  PKR: 160.16046
                  PLN: 3.7535
                  PYG: 6890.343
                  QAR: 3.64022
                  RON: 4.02672
                  RSD: 96.9947
                  RUB: 73.59569
                  RWF: 972.40542
                  SAR: 3.74834
                  SCR: 21.7415
                  SDG: 55.12079
                  SEK: 8.39445
                  SGD: 1.33084
                  SHP: 0.73605
                  SLL: 10117.25305
                  SOS: 585.66171
                  SRD: 14.0817
                  SYP: 1257.58133
                  SZL: 15.23848
                  THB: 30.10158
                  TJS: 11.37737
                  TMT: 3.49448
                  TND: 2.7086
                  TOP: 2.27536
                  TRY: 7.45083
                  TTD: 6.74407
                  TWD: 28.03621
                  TZS: 2317.83454
                  UAH: 28.17938
                  UGX: 3704.99043
                  USD: 1
                  UYU: 42.4356
                  UZS: 10493.30193
                  VND: 23216.10481
                  VUV: 107.05138
                  WST: 2.54085
                  XAF: 542.97807
                  XCD: 2.69954
                  XDR: 0.69699
                  XOF: 542.97807
                  XPF: 98.70455
                  YER: 246.27558
                  ZAR: 15.20595
                  ZMW: 21.37472
                updated: '2021-01-16 17:14:51'
                ms: 13
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "429":
          description: "Rate limit exceeded"
  /convert:
    get:
      description: "Convert an amount of one currency into another currency"
      parameters:
        - name: "from"
          in: "query"
          description: "Base currency 3-letter symbol, defaults to USD"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/Currency"
        - name: "to"
          in: "query"
          description: "Target currency 3-letter symbol"
          required: true
          schema:
            $ref: "#/components/schemas/Currency"
        - name: "amount"
          in: "query"
          description: "Amount of source currency to convert"
          required: true
          schema:
            type: number
            format: float
            minimum: 0.01
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    $ref: "#/components/schemas/Currency"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  amount:
                    type: number
                    format: float
                  result:
                    type: object
                    minProperties: 2
                    maxProperties: 2
                    properties:
                      rate:
                        type: number
                        format: float
                    additionalProperties:
                      type: number
                      format: float
              example:
                base: USD
                amount: 199.5
                result:
                  EUR: 164.29
                  rate: 0.82353
                ms: 7
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "429":
          description: "Rate limit exceeded"
  /historical:
    get:
      description: "Fetch exchange rates for a date in the past"
      parameters:
        - name: "date"
          in: "query"
          description: "UTC date in YYYY-MM-DD format. Must be in the past and within the last 150 days."
          required: true
          schema:
            $ref: "#/components/schemas/Date"
        - name: "from"
          in: "query"
          description: "Base currency 3-letter symbol, defaults to USD"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/Currency"
        - name: "to"
          in: "query"
          description: "Target currencies, comma separated list of 3-letter symbols. Defaults to all currencies if omitted"
          required: false
          allowEmptyValue: true
          schema:
            $ref: "#/components/schemas/CurrencyList"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    $ref: "#/components/schemas/Currency"
                  date:
                    $ref: "#/components/schemas/Date"
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  results:
                    type: object
                    minProperties: 130
                    additionalProperties:
                      type: number
                      format: float
              example:
                date: '2021-01-16'
                base: USD
                results:
                  AED: 3.67297
                  AFN: 77.11468
                  ALL: 101.78125
                  AMD: 523.67143
                  ANG: 1.78691
                  AOA: 653.45356
                  ARS: 85.74709
                  AUD: 1.29806
                  AWG: 1.79943
                  AZN: 1.70727
                  BAM: 1.62182
                  BBD: 1.99941
                  BDT: 84.84175
                  BGN: 1.61063
                  BHD: 0.37612
                  BIF: 1943.32401
                  BMD: 0.99926
                  BND: 1.32953
                  BOB: 6.88532
                  BRL: 5.29479
                  BSD: 1.00177
                  BTN: 73.22317
                  BWP: 10.98351
                  BZD: 2.01472
                  CAD: 1.27357
                  CDF: 1977.04254
                  CHF: 0.8912
                  CLF: 0.02491
                  CLP: 734.84469
                  CNH: 6.47453
                  CNY: 6.48079
                  COP: 3461.79891
                  CUP: 24.99558
                  CVE: 90.9024
                  CZK: 21.65759
                  DJF: 177.94053
                  DKK: 6.15612
                  DOP: 58.27175
                  DZD: 133.63021
                  EGP: 15.64449
                  ERN: 15.1347
                  ETB: 39.35227
                  EUR: 0.82791
                  FJD: 2.05329
                  FKP: 0.73605
                  GBP: 0.73605
                  GEL: 3.30208
                  GHS: 5.78235
                  GIP: 0.73605
                  GMD: 51.76064
                  GNF: 10080.74488
                  GTQ: 7.78301
                  GYD: 210.42985
                  HKD: 7.75357
                  HNL: 24.12042
                  HRK: 6.19682
                  HTG: 75.90461
                  HUF: 298.21139
                  IDR: 14054.17341
                  ILS: 3.2719
                  INR: 73.16164
                  IQD: 1458.41307
                  IRR: 42031.79744
                  ISK: 129.4936
                  JMD: 144.24702
                  JOD: 0.70779
                  JPY: 103.87016
                  KES: 109.70116
                  KGS: 75.50493
                  KHR: 4047.84337
                  KMF: 406.08715
                  KPW: 900.13249
                  KRW: 1102.13455
                  KWD: 0.30318
                  KYD: 0.81923
                  KZT: 418.85765
                  LAK: 9308.2585
                  LBP: 1509.38466
                  LKR: 194.62682
                  LRD: 167.93022
                  LSL: 15.21787
                  LYD: 4.45341
                  MAD: 8.91064
                  MDL: 17.18902
                  MGA: 3762.10805
                  MKD: 51.00986
                  MMK: 1331.8784
                  MNT: 2853.84955
                  MOP: 8.01634
                  MRU: 36.41764
                  MUR: 39.84837
                  MVR: 15.66392
                  MWK: 773.70087
                  MXN: 19.79604
                  MYR: 4.03732
                  MZN: 74.77698
                  NAD: 15.18769
                  NGN: 380.3327
                  NOK: 8.56904
                  NPR: 117.3193
                  NZD: 1.40232
                  OMR: 0.38422
                  PAB: 0.99926
                  PEN: 3.60165
                  PGK: 3.52819
                  PHP: 48.06492
                  PKR: 160.16046
                  PLN: 3.7535
                  PYG: 6890.343
                  QAR: 3.64022
                  RON: 4.02672
                  RSD: 96.9947
                  RUB: 73.59569
                  RWF: 972.40542
                  SAR: 3.74834
                  SCR: 21.7415
                  SDG: 55.12079
                  SEK: 8.39445
                  SGD: 1.33084
                  SHP: 0.73605
                  SLL: 10117.25305
                  SOS: 585.66171
                  SRD: 14.0817
                  SYP: 1257.58133
                  SZL: 15.23848
                  THB: 30.10158
                  TJS: 11.37737
                  TMT: 3.49448
                  TND: 2.7086
                  TOP: 2.27536
                  TRY: 7.45083
                  TTD: 6.74407
                  TWD: 28.03621
                  TZS: 2317.83454
                  UAH: 28.17938
                  UGX: 3704.99043
                  USD: 1
                  UYU: 42.4356
                  UZS: 10493.30193
                  VND: 23216.10481
                  VUV: 107.05138
                  WST: 2.54085
                  XAF: 542.97807
                  XCD: 2.69954
                  XDR: 0.69699
                  XOF: 542.97807
                  XPF: 98.70455
                  YER: 246.27558
                  ZAR: 15.20595
                  ZMW: 21.37472
                ms: 13
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found - We do not have historical rates for the requested date and currency pair"
        "429":
          description: "Rate limit exceeded"
  /currencies:
    get:
      description: "Fetch a list of supported currencies"
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                  ms:
                    $ref: "#/components/schemas/ResponseTime"
                  currencies:
                    type: object
                    minProperties: 130
                    additionalProperties:
                      type: string
              example:
                currencies:
                  AED: United Arab Emirates Dirham
                  AFN: Afghan Afghani
                  ALL: Albanian Lek
                  AMD: Armenian Dram
                  ANG: Dutch Guilders
                  AOA: Angolan Kwanza
                  ARS: Argentine Peso
                  AUD: Australian Dollar
                  AWG: Aruban Florin
                  AZN: Azerbaijani Manat
                  BAM: Bosnia-Herzegovina Convertible Mark
                  BBD: Barbadian Dollar
                  BDT: Bangladeshi Taka
                  BGN: Bulgarian Lev
                  BHD: Bahraini Dinar
                  BIF: Burundian Franc
                  BMD: Bermudian Dollar
                  BND: Bruneian Dollar
                  BOB: Bolivian Boliviano
                  BRL: Brazilian Real
                  BSD: Bahamian Dollar
                  BTN: Bhutanese Ngultrum
                  BWP: Botswanan Pula
                  BZD: Belizean Dollar
                  CAD: Canadian Dollar
                  CDF: Congolese Franc
                  CHF: Swiss Franc
                  CLF: Chilean Unit of Account UF
                  CLP: Chilean Peso
                  CNH: Chinese Yuan Offshore
                  CNY: Chinese Yuan
                  COP: Colombian Peso
                  CUP: Cuban Peso
                  CVE: Cape Verdean Escudo
                  CZK: Czech Republic Koruna
                  DJF: Djiboutian Franc
                  DKK: Danish Krone
                  DOP: Dominican Peso
                  DZD: Algerian Dinar
                  EGP: Egyptian Pound
                  ERN: Eritrean Nakfa
                  ETB: Ethiopian Birr
                  EUR: Euro
                  FJD: Fijian Dollar
                  FKP: Falkland Islands Pound
                  GBP: British Pound Sterling
                  GEL: Georgian Lari
                  GHS: Ghanaian Cedi
                  GIP: Gibraltar Pound
                  GMD: Gambian Dalasi
                  GNF: Guinean Franc
                  GTQ: Guatemalan Quetzal
                  GYD: Guyanaese Dollar
                  HKD: Hong Kong Dollar
                  HNL: Honduran Lempira
                  HRK: Croatian Kuna
                  HTG: Haitian Gourde
                  HUF: Hungarian Forint
                  IDR: Indonesian Rupiah
                  ILS: Israeli New Sheqel
                  INR: Indian Rupee
                  IQD: Iraqi Dinar
                  IRR: Iranian Rial
                  ISK: Icelandic Krona
                  JMD: Jamaican Dollar
                  JOD: Jordanian Dinar
                  JPY: Japanese Yen
                  KES: Kenyan Shilling
                  KGS: Kyrgystani Som
                  KHR: Cambodian Riel
                  KMF: Comorian Franc
                  KPW: North Korean Won
                  KRW: South Korean Won
                  KWD: Kuwaiti Dinar
                  KYD: Caymanian Dollar
                  KZT: Kazakhstani Tenge
                  LAK: Laotian Kip
                  LBP: Lebanese Pound
                  LKR: Sri Lankan Rupee
                  LRD: Liberian Dollar
                  LSL: Basotho Maloti
                  LYD: Libyan Dinar
                  MAD: Moroccan Dirham
                  MDL: Moldovan Leu
                  MGA: Malagasy Ariary
                  MKD: Macedonian Denar
                  MMK: Myanma Kyat
                  MNT: Mongolian Tugrik
                  MOP: Macanese Pataca
                  MRU: Mauritanian Ouguiya
                  MUR: Mauritian Rupee
                  MVR: Maldivian Rufiyaa
                  MWK: Malawian Kwacha
                  MXN: Mexican Peso
                  MYR: Malaysian Ringgit
                  MZN: Mozambican Metical
                  NAD: Namibian Dollar
                  NGN: Nigerian Naira
                  NOK: Norwegian Krone
                  NPR: Nepalese Rupee
                  NZD: New Zealand Dollar
                  OMR: Omani Rial
                  PAB: Panamanian Balboa
                  PEN: Peruvian Nuevo Sol
                  PGK: Papua New Guinean Kina
                  PHP: Philippine Peso
                  PKR: Pakistani Rupee
                  PLN: Polish Zloty
                  PYG: Paraguayan Guarani
                  QAR: Qatari Rial
                  RON: Romanian Leu
                  RSD: Serbian Dinar
                  RUB: Russian Ruble
                  RWF: Rwandan Franc
                  SAR: Saudi Arabian Riyal
                  SCR: Seychellois Rupee
                  SDG: Sudanese Pound
                  SEK: Swedish Krona
                  SGD: Singapore Dollar
                  SHP: Saint Helena Pound
                  SLL: Sierra Leonean Leone
                  SOS: Somali Shilling
                  SRD: Surinamese Dollar
                  SYP: Syrian Pound
                  SZL: Swazi Emalangeni
                  THB: Thai Baht
                  TJS: Tajikistani Somoni
                  TMT: Turkmenistani Manat
                  TND: Tunisian Dinar
                  TOP: Tongan Pa'anga
                  TRY: Turkish Lira
                  TTD: Trinidad and Tobago Dollar
                  TWD: Taiwan New Dollar
                  TZS: Tanzanian Shilling
                  UAH: Ukrainian Hryvnia
                  UGX: Ugandan Shilling
                  USD: United States Dollar
                  UYU: Uruguayan Peso
                  UZS: Uzbekistan Som
                  VND: Vietnamese Dong
                  VUV: Ni-Vanuatu Vatu
                  WST: Samoan Tala
                  XAF: CFA Franc BEAC
                  XCD: East Caribbean Dollar
                  XDR: Special Drawing Rights
                  XOF: CFA Franc BCEAO
                  XPF: CFP Franc
                  YER: Yemeni Rial
                  ZAR: South African Rand
                  ZMW: Zambian Kwacha
                ms: 8
        "400":
          description: "Bad Request"
        "401":
          description: "Not Authorized"
        "429":
          description: "Rate limit exceeded"
components:
  schemas:
    Currency:
      type: "string"
      pattern: "[A-Z]{3}"
      description: "Three letter currency code"
    CurrencyList:
      type: "string"
      pattern: "[A-Z]{3}(,[A-Z]{3})*"
      description: "A comma-separated list of three letter currency codes"
    ResponseTime:
      type: number
      format: int32
      description: "Server response time in milliseconds"
    DateTime:
      type: string
      pattern: "[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}"
      description: "UTC/GMT datetime YYYY-MM-DD HH:MM:SS"
    Date:
      type: string
      pattern: "[0-9]{4}-[0-9]{2}-[0-9]{2}"
      description: "UTC/GMT date YYYY-MM-DD"
